### PR TITLE
Prisma

### PR DESCRIPTION
**Pull request by keonik**
Don't merge into master. Creating for review purposes

### CODE REVIEW

**Comment by heystevegray** [comment]
@keonik Looks good to me. You said you picked `sqlite` in the `schema.prisma` file for testing, but I think it would be more valuable to have the postgres stuff already. If we are making a CLI, we could prompt users for the postgres env variables maybe? Or you could skip them. But you would have to update the postgres url in the env file.

**Comment by keonik** [comment]
@tonygilkerson Are there any things in the mile two staging deployment setup that is proprietary? [Example](https://gitlab.com/mile-two/resources/mile-two-resources/-/tree/master/configs/nextjs). 

@heystevegray options moving forward I can think of...
1. Include setup for Postgres w/ Mile Two's whole setup (docker, postgres, staging charts files)
2. Keep the working example with sqlite and move the access to our postgres setup to the CLI as a credential required step

**Comment by tonygilkerson** [comment]
@keonik re: "mile two staging deployment setup that is proprietary" The tools we use are all open source if that is what you are asking.  I don't have any context for what I am looking at.  Are you trying to move/re-implement the CI pipelines we have in gitlab to some other system or are you just trying to integrate it with GitHub?  In either case it should be possible, we are not doing any thing special, and all the tools used are OSS.  If you give me more context maybe I can give better feedback.

**Review by heystevegray — APPROVED** [review]
lgtm

**Pull request merged**
